const userActionTypes = {
    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',

    SIGNIN_FAILED: 'SIGNIN_FAILED',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    CHECK_USER: 'CHECK_USER',

    SIGN_OUT_START : 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: ' SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILED: ' SIGN_OUT_FAILED',
}

export default userActionTypes