const userActionTypes = {
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',

    SIGN_IN_FAILED: 'SIGN_IN_FAILED',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    CHECK_USER: 'CHECK_USER',

    SIGN_OUT_START : 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: ' SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILED: ' SIGN_OUT_FAILED',

    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCESS: 'SIGN_UP_SUCESS',
    SING_UP_FAILED: 'SIGN_UP_FAILED',
}

export default userActionTypes